#!/bin/sh
echo "Launching ElectrumXLTFN server..."
USERNAME=$(envdir ./env printenv USERNAME)
ELECTRUMXLTFN=$(envdir ./env printenv ELECTRUMXLTFN)
ulimit -n 4000 && exec 2>&1 envdir ./env envuidgid $USERNAME python3 $ELECTRUMXLTFN
